### ISSUE TITLE
Encoding problem

### ISSUE THREAD

**Issue by maxbeegee** [alswl/imap-auto-forward#1]
For some emails the line
`data[0][1].decode('UTF-8')`

made problems (error: "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf6 in position 4160: invalid start byte").

I fixed it by changing it to:

```
           msg = email.parser.BytesParser().parsebytes(data[0][1])
            # get a bytes object containing the base64-decoded message
            textbytes = msg.get_payload(decode=True)

            # get the content charset
            content_charset = msg.get_content_charset()

            # decode the text to obtain a string object
            email_data = data[0][1].decode(content_charset)

```

which I found here: https://stackoverflow.com/questions/25007366/handling-encoded-messages-with-python-and-imaplib

However, I am not sure if this breaks something else...? So I did not want to make a pull request.

In any case, thanks a lot for the script. Very useful!

**Comment by alswl** [comment]
Because I'm lived in China, so all message is encoded by `utf-8`.
I'm glad to receive a pull request.
