### ISSUE TITLE
Forward as inline attachement

### ISSUE THREAD

**Issue by bonelifer** [alswl/imap-auto-forward#2]
Is there a way to forward an email based on subject(contains) and email address as inline attachment so images show up to the person who gets forwarded to, but not mark mail as read so the main account also downloads the email

**Comment by alswl** [comment]
Sure, If you want NOT modify the original mails, you should use DB to persist the list of forwarded mails. But this project is a DB-free script, it use `is_read` to mark if the email had forwarded.

If you filter mails by subject or other keywords without a persistence mail status list, you will forward a lot of duplicated mails.
